[#IR-114] Add ordering in all list APIs
iReflect/reflect-app pull request #102
Opened 2018-03-22 10:59 UTC by chetanyakan

2018-03-22 12:35 UTC, anmolghosh requested changes
- Re-discuss the fields to be used for ordering
- Also re-check order for each API separately
- Check if any API requires composite ordering

2018-03-26 13:59 UTC, ishugupta92 commented
@anmolghosh Updated PR with updated ordering. Please Review.

2018-03-26 15:25 UTC, anmolghosh submitted a review, later dismissed

2018-03-26 15:25 UTC, anmolghosh commented on apps/retrospective/services/retrospective_feedback.go
> +		Order("resolved_at DESC, added_at DESC, created_at DESC").
this should be on basic of goal tyhpe

2018-03-26 15:25 UTC, anmolghosh commented on apps/retrospective/services/sprint.go
> +		Order("end_date DESC").
re-visit this, on basis of end date

2018-03-26 15:25 UTC, anmolghosh commented on apps/retrospective/services/sprint.go
> +		Order("users.first_name, users.last_name").
append id

2018-03-26 15:25 UTC, anmolghosh commented on apps/user/services/team.go
> +		Order("teams.name")
append created_At desc

2018-03-26 15:32 UTC, ishugupta92 commented on apps/retrospective/services/retrospective_feedback.go
> +		Order("resolved_at DESC, added_at DESC, created_at DESC").
Done

2018-03-26 15:33 UTC, ishugupta92 commented on apps/retrospective/services/sprint.go
> +		Order("end_date DESC").
Done

2018-03-26 15:34 UTC, ishugupta92 commented on apps/user/services/team.go
> +		Order("teams.name")
Done

2018-03-26 15:38 UTC, anmolghosh approved these changes

2018-03-26 15:39 UTC, merged