IR-250: Allow admin users to access the retrospective app when they are not part of it
iReflect/reflect-app pull request #166
Opened 2018-12-24 09:36 UTC by naveenkumar1012

2018-12-24 14:06 UTC, himanshu-garg-165 requested changes
Please make sure all the APIs are covered and the admin is able to view/edit everything irrespective of he being in a team or not. Also, ensure that the imports are ordered and grouped properly.

2018-12-24 14:06 UTC, himanshu-garg-165 commented on apps/retrospective/services/permission.go
> +		Where("users.id=?", userID).
Please add spaces around the `=` sign.

2018-12-24 14:06 UTC, himanshu-garg-165 commented on apps/retrospective/services/retrospective.go
> +	userID uint, perPageString string, pageString string, isAdmin bool) (
Do we really need to break the line here? If yes, please ensure it adheres to the standards.

2018-12-24 14:06 UTC, himanshu-garg-165 commented on apps/retrospective/services/retrospective.go
> +	if isAdmin {
Please common out the base query-set.

2018-12-26 08:51 UTC, naveenkumar1012 commented on apps/retrospective/services/permission.go
> +		Where("users.id=?", userID).
We have used the same format everywhere in this file. But, I agree we should add spaces around the `=`. I'll add the space everywhere in this file.

2018-12-26 08:53 UTC, naveenkumar1012 commented on apps/retrospective/services/retrospective.go
> +	userID uint, perPageString string, pageString string, isAdmin bool) (
Are we not following 80 or 100 chars per line? If not, I'll make this in one line.

2018-12-26 08:53 UTC, naveenkumar1012 commented on apps/retrospective/services/retrospective.go
> +	if isAdmin {
Sure.

2018-12-26 10:32 UTC, himanshu-garg-165 commented on apps/retrospective/services/retrospective.go
> +	userID uint, perPageString string, pageString string, isAdmin bool) (
No, we are not following any such standard as of now (I believe there is no such standard in Go). But if there is some standard in the Go community, then we should follow it.

2018-12-28 09:02 UTC, himanshu-garg-165 reviewed
PR looks good. Apparently, there are a few formatting issues, please run `make fmt` to fix them.

2018-12-28 10:28 UTC, himanshu-garg-165 approved these changes

2018-12-28 10:29 UTC, merged