[#IR-304] Change google+ login to google login.
iReflect/reflect-app pull request #167
Opened 2019-02-04 17:27 UTC by chahat-arora

2019-02-05 10:58 UTC, himanshu-garg-165 requested changes

2019-02-05 10:58 UTC, himanshu-garg-165 commented on apps/user/services/authentication.go
> +	googleAPI "google.golang.org/api/oauth2/v2"
```suggestion
	googleOAuthAPI "google.golang.org/api/oauth2/v2"
```

2019-02-05 14:30 UTC, chahat-arora commented on apps/user/services/authentication.go
> +	googleAPI "google.golang.org/api/oauth2/v2"
done.

2019-02-06 06:50 UTC, himanshu-garg-165 approved these changes

2019-02-06 07:02 UTC, merged