[#IR-326] As a user, I can see Actual Hours of the sprint cards
iReflect/reflect-app pull request #182
Opened 2019-04-08 10:14 UTC by Ravi2714

2019-04-09 06:40 UTC, chahat-arora requested changes
Remove `dump.rdb` file.

2019-04-09 06:40 UTC, chahat-arora commented on apps/retrospective/services/sprint.go
> +		"COUNT(DISTINCT(tasks.id)) AS total_count, COALESCE(SUM(sprint_member_tasks.points_earned),0) AS total_points_earned, COALESCE(SUM(sprint_member_tasks.time_spent_minutes),0) AS actual_hours").
```suggestion
		`COUNT(DISTINCT(tasks.id)) AS total_count,
		 COALESCE(SUM(sprint_member_tasks.points_earned),0) AS total_points_earned, 
		 COALESCE(SUM(sprint_member_tasks.time_spent_minutes),0) AS actual_hours`).
```

2019-04-10 10:36 UTC, himanshu-garg-165 requested changes

2019-04-10 10:36 UTC, himanshu-garg-165 commented on apps/retrospective/services/sprint.go
> +	   COALESCE(SUM(sprint_member_tasks.points_earned),0) AS total_points_earned,
```suggestion
		COALESCE(SUM(sprint_member_tasks.points_earned),0) AS total_points_earned,
```

2019-04-12 07:12 UTC, Ravi2714 commented on apps/retrospective/services/sprint.go
> +		"COUNT(DISTINCT(tasks.id)) AS total_count, COALESCE(SUM(sprint_member_tasks.points_earned),0) AS total_points_earned, COALESCE(SUM(sprint_member_tasks.time_spent_minutes),0) AS actual_hours").
done

2019-04-12 07:12 UTC, Ravi2714 commented on apps/retrospective/services/sprint.go
> +	   COALESCE(SUM(sprint_member_tasks.points_earned),0) AS total_points_earned,
done

2019-04-12 13:40 UTC, chahat-arora requested changes

2019-04-12 13:40 UTC, chahat-arora commented on apps/retrospective/serializers/sprint.go
> +	retroModels "github.com/iReflect/reflect-app/apps/retrospective/models"
sort imports properly.

2019-04-12 13:40 UTC, chahat-arora commented on apps/retrospective/services/sprint.go
> +	"strings"
sort imports properly.

2019-04-16 12:48 UTC, Ravi2714 commented on apps/retrospective/serializers/sprint.go
> +	retroModels "github.com/iReflect/reflect-app/apps/retrospective/models"
done

2019-04-16 12:48 UTC, Ravi2714 commented on apps/retrospective/services/sprint.go
> +	"strings"
done

2019-04-17 05:56 UTC, chahat-arora requested changes
Please, back merge develop.

2019-04-25 10:01 UTC, himanshu-garg-165 approved these changes

2019-05-23 05:30 UTC, chahat-arora approved these changes

2019-05-28 07:11 UTC, himanshu-garg-165 approved these changes

2019-06-03 15:01 UTC, merged