Removed dump.rdb file
iReflect/reflect-app pull request #186
Opened 2019-04-10 12:19 UTC by chahat-arora

2019-04-10 12:41 UTC, himanshu-garg-165 requested changes

2019-04-10 12:41 UTC, himanshu-garg-165 commented on .gitignore
> +.rdb
Would it really make an effect?

2019-04-10 15:18 UTC, chahat-arora commented on .gitignore
> +.rdb
changed

2019-04-11 06:54 UTC, himanshu-garg-165 approved these changes

2019-04-11 06:57 UTC, merged