[#IR-333]As a dev, I have added show all retro button for an admin to see all retrospectives
iReflect/reflect-app pull request #188
Opened 2019-04-11 10:16 UTC by Ravi2714

2019-04-12 12:38 UTC, chahat-arora requested changes

2019-04-12 12:38 UTC, chahat-arora commented on apps/retrospective/services/retrospective.go
> +	"net/http"
sort imports properly.

2019-04-12 12:38 UTC, chahat-arora commented on apps/retrospective/services/retrospective.go
> +		Where("user_teams.deleted_at IS NULL").
no need of this.

2019-04-12 12:38 UTC, chahat-arora commented on apps/retrospective/services/retrospective.go
> +			Where("retrospectives.team_id NOT IN (?)", userTeamQuery).
please, try to optimize this.

2019-04-12 12:38 UTC, chahat-arora commented on apps/retrospective/services/retrospective.go
> +		Where("retrospectives.team_id IN (?)", userTeamQuery).
same here.

2019-04-12 12:38 UTC, chahat-arora commented on apps/retrospective/services/retrospective.go
> +			Where("retrospectives.team_id NOT IN (?)", userTeamQuery).
handle error also.

2019-04-15 14:34 UTC, Ravi2714 commented on apps/retrospective/services/retrospective.go
> +	"net/http"
done

2019-04-15 14:34 UTC, Ravi2714 commented on apps/retrospective/services/retrospective.go
> +		Where("user_teams.deleted_at IS NULL").
removed

2019-04-15 14:34 UTC, Ravi2714 commented on apps/retrospective/services/retrospective.go
> +		Where("retrospectives.team_id IN (?)", userTeamQuery).
changed

2019-04-15 14:34 UTC, Ravi2714 commented on apps/retrospective/services/retrospective.go
> +			Where("retrospectives.team_id NOT IN (?)", userTeamQuery).
done

2019-05-23 07:58 UTC, chahat-arora approved these changes

2019-05-28 07:12 UTC, himanshu-garg-165 approved these changes

2019-06-03 15:05 UTC, merged