[#IR-350] As a dev, I have Fixed the bugs in release v0.2.7
iReflect/reflect-app pull request #200
Opened 2019-06-12 14:10 UTC by chahat-arora

2019-06-13 12:15 UTC, sandipagarwal requested changes

2019-06-13 12:15 UTC, sandipagarwal commented on apps/retrospective/services/retrospective_feedback.go
> +		expectedAt := sprint.EndDate.Add(absEndDate.Sub(absStartDate))
It should an additional 1.

2019-06-17 10:20 UTC, chahat-arora commented on apps/retrospective/services/retrospective_feedback.go
> +		expectedAt := sprint.EndDate.Add(absEndDate.Sub(absStartDate))
Done.

2019-06-17 16:51 UTC, himanshu-garg-165 approved these changes

2019-06-18 07:10 UTC, sandipagarwal approved these changes

2019-06-18 10:24 UTC, merged